<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SitiosPersonal.Entities\SitiosPersonal.Entities.csproj" />
    <ProjectReference Include="..\SitiosPersonal.Repository\SitiosPersonal.Repository.csproj" />
    <ProjectReference Include="..\SitiosPersonal.Services\SitiosPersonal.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\General\" />
    <Folder Include="Pages\Seguridad\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

</Project>
